// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    ExportXlsxBtn: typeof import('./src/components/ExportXlsxBtn.vue')['default']
    FullLoading: typeof import('./src/components/FullLoading.vue')['default']
    LoadAll: typeof import('./src/components/LoadAll.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchUser: typeof import('./src/components/SearchUser.vue')['default']
    SelectMenu: typeof import('./src/components/SelectMenu.vue')['default']
    ToBottom: typeof import('./src/components/ToBottom.vue')['default']
    TopTitle: typeof import('./src/components/TopTitle.vue')['default']
    UploadFiles: typeof import('./src/components/UploadFiles.vue')['default']
    ValidateText: typeof import('./src/components/ValidateText.vue')['default']
  }
}

export {}
